system:
  spawn-player-one: "world;1;100;1;0;0"
  spawn-player-two: "world;2;100;1;0;0"
  spawn-waiting: "world;3;100;1;0;0"
  min-players: 10
  max-players: 40
language:
  duel-help-message:
    - "* /duel join — Join the current duel!"
    - "* /duel left — Left the duel!"
  duel-started:
    - "A duel started!"
    - "type /duel join to join the event!"
  duel-already-started: "A duel is already started!"
  joined-duel:
events:
  event-one:
    date: "2/01/2022 22:40"
    can-bet: true
    rewards:
      - "say Hi!"
  event-two:
    date: "1/01/2022 22:40"
    can-bet: true
    rewards:
      - "say Hi!"
